services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit-host
    container_name: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  apiservice:
    build:
      context: .
      dockerfile: Sally.ApiService/Dockerfile
    ports:
      - "9000-9002:9000-9002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    restart: always

  discordbot:
    build:
      context: .
      dockerfile: Sally.DiscordBot/Dockerfile
    volumes:
      - bot-config:/etc/sally
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    restart: always

volumes:
  bot-config: