name: Build

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '/*.{png,jpg,jpeg,svg}'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c release
