name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Restore
        run: dotnet restore

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ';'
          files: src/**

      - name: Run ReSharper
        uses: muno92/resharper_inspectcode@1.11.10
        with:
          solutionPath: ./Sally.sln
          include: ${{ steps.changed-files.outputs.all_changed_files }}
          ignoreIssueType: |
            RedundantNameQualifier
            UnusedType.Global
            UnusedMember.Local
            UnusedMember.Global
            MemberCanBeMadeStatic.Local
            AutoPropertyCanBeMadeGetOnly.Global
            MemberCanBePrivate.Global
            SwitchStatementMissingSomeEnumCasesNoDefault